// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: BaseProtocol.proto

package BaseProtocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgID int32

const (
	MsgID_Base_Unknow     MsgID = 0
	MsgID_ServerConnect   MsgID = 1
	MsgID_ServerHeartbeat MsgID = 2
)

// Enum value maps for MsgID.
var (
	MsgID_name = map[int32]string{
		0: "Base_Unknow",
		1: "ServerConnect",
		2: "ServerHeartbeat",
	}
	MsgID_value = map[string]int32{
		"Base_Unknow":     0,
		"ServerConnect":   1,
		"ServerHeartbeat": 2,
	}
)

func (x MsgID) Enum() *MsgID {
	p := new(MsgID)
	*p = x
	return p
}

func (x MsgID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgID) Descriptor() protoreflect.EnumDescriptor {
	return file_BaseProtocol_proto_enumTypes[0].Descriptor()
}

func (MsgID) Type() protoreflect.EnumType {
	return &file_BaseProtocol_proto_enumTypes[0]
}

func (x MsgID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgID.Descriptor instead.
func (MsgID) EnumDescriptor() ([]byte, []int) {
	return file_BaseProtocol_proto_rawDescGZIP(), []int{0}
}

type ServerConnectMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerType uint32 `protobuf:"varint,1,opt,name=serverType,proto3" json:"serverType,omitempty"`
	ServerID   uint64 `protobuf:"varint,2,opt,name=serverID,proto3" json:"serverID,omitempty"`
}

func (x *ServerConnectMsg) Reset() {
	*x = ServerConnectMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_BaseProtocol_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerConnectMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerConnectMsg) ProtoMessage() {}

func (x *ServerConnectMsg) ProtoReflect() protoreflect.Message {
	mi := &file_BaseProtocol_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerConnectMsg.ProtoReflect.Descriptor instead.
func (*ServerConnectMsg) Descriptor() ([]byte, []int) {
	return file_BaseProtocol_proto_rawDescGZIP(), []int{0}
}

func (x *ServerConnectMsg) GetServerType() uint32 {
	if x != nil {
		return x.ServerType
	}
	return 0
}

func (x *ServerConnectMsg) GetServerID() uint64 {
	if x != nil {
		return x.ServerID
	}
	return 0
}

type ServerHeartBeatMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Heartbeat uint32 `protobuf:"varint,1,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`
}

func (x *ServerHeartBeatMsg) Reset() {
	*x = ServerHeartBeatMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_BaseProtocol_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerHeartBeatMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerHeartBeatMsg) ProtoMessage() {}

func (x *ServerHeartBeatMsg) ProtoReflect() protoreflect.Message {
	mi := &file_BaseProtocol_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerHeartBeatMsg.ProtoReflect.Descriptor instead.
func (*ServerHeartBeatMsg) Descriptor() ([]byte, []int) {
	return file_BaseProtocol_proto_rawDescGZIP(), []int{1}
}

func (x *ServerHeartBeatMsg) GetHeartbeat() uint32 {
	if x != nil {
		return x.Heartbeat
	}
	return 0
}

var File_BaseProtocol_proto protoreflect.FileDescriptor

var file_BaseProtocol_proto_rawDesc = []byte{
	0x0a, 0x12, 0x42, 0x61, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4e, 0x0a, 0x10, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x49, 0x44, 0x22, 0x32, 0x0a, 0x12, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x48, 0x65,
	0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x68, 0x65,
	0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x68,
	0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x2a, 0x40, 0x0a, 0x05, 0x4d, 0x73, 0x67, 0x49,
	0x44, 0x12, 0x0f, 0x0a, 0x0b, 0x42, 0x61, 0x73, 0x65, 0x5f, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77,
	0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x48,
	0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x10, 0x02, 0x42, 0x1d, 0x48, 0x03, 0x5a, 0x19,
	0x42, 0x61, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x3b, 0x42, 0x61, 0x73,
	0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_BaseProtocol_proto_rawDescOnce sync.Once
	file_BaseProtocol_proto_rawDescData = file_BaseProtocol_proto_rawDesc
)

func file_BaseProtocol_proto_rawDescGZIP() []byte {
	file_BaseProtocol_proto_rawDescOnce.Do(func() {
		file_BaseProtocol_proto_rawDescData = protoimpl.X.CompressGZIP(file_BaseProtocol_proto_rawDescData)
	})
	return file_BaseProtocol_proto_rawDescData
}

var file_BaseProtocol_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_BaseProtocol_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_BaseProtocol_proto_goTypes = []interface{}{
	(MsgID)(0),                 // 0: MsgID
	(*ServerConnectMsg)(nil),   // 1: ServerConnectMsg
	(*ServerHeartBeatMsg)(nil), // 2: ServerHeartBeatMsg
}
var file_BaseProtocol_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_BaseProtocol_proto_init() }
func file_BaseProtocol_proto_init() {
	if File_BaseProtocol_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_BaseProtocol_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerConnectMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_BaseProtocol_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerHeartBeatMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_BaseProtocol_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_BaseProtocol_proto_goTypes,
		DependencyIndexes: file_BaseProtocol_proto_depIdxs,
		EnumInfos:         file_BaseProtocol_proto_enumTypes,
		MessageInfos:      file_BaseProtocol_proto_msgTypes,
	}.Build()
	File_BaseProtocol_proto = out.File
	file_BaseProtocol_proto_rawDesc = nil
	file_BaseProtocol_proto_goTypes = nil
	file_BaseProtocol_proto_depIdxs = nil
}
